USE [COMORIENTE]
GO
/****** Object:  StoredProcedure [dbo].[PagosSIESAMerge]    Script Date: 12/07/2024 10:30:17 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[PagosSIESAMerge]
AS
BEGIN



--DELETE AD_TBL_RC
--DELETE AD_TBL_RC_CAJA
--DELETE AD_TBL_RC_CXC

DECLARE @F_CIA VARCHAR(3) = '001'
--=================================================================================
--Configuracion R.C y otros ingresos V2
-- F_CONSEC_AUTO_REG
-- Indica si el numero consecutivo de docto es manual o automático
-- 0=Manual, significa que respecta el consecutivo asignado en el plano, 1=Automático, significa que el consecutivo es recalculado con base en la tabla de consecutivos de docto.
DECLARE @F_CONSEC_AUTO_REG VARCHAR(1) = '1'
-----------------------------------------------------------------------------------
-- F357_ID_FE
-- Concepto de flujo de efectivo
-- Valida en maestro, concepto de flujo de efectivo, es obligatorio si la caja no tiene uno por defecto.
DECLARE @F357_ID_FE VARCHAR(13) = '1101'
-----------------------------------------------------------------------------------
-- F350_ID_CLASE_DOCTO
-- Clase interna del documento
-- 13=Recibo de caja, 14=Otros ingresos
DECLARE @F350_ID_CLASE_DOCTO VARCHAR(5) = '00013'
-----------------------------------------------------------------------------------
-- F350_IND_ESTADO
-- Estado del documento
-- 1=Aprobado, 2=Anulado
DECLARE @F350_IND_ESTADO VARCHAR(1) = '1'
-----------------------------------------------------------------------------------
--F357_IND_VALIDA_MEDPAGO
-- Indica si se controla valor en medios de pago
-- 0 = No valida; 1 = Valida
DECLARE @F357_IND_VALIDA_MEDPAGO VARCHAR(1) = '0'
--=================================================================================
--Configuracion Caja V2
--=================================================================================
--Configuracion CxC V2
-- 
DECLARE @F353_ID_AUXILIAR_DOCTO_CRUCE VARCHAR(20) = '13050501'
--=================================================================================
--INSERT INTO AD_TBL_RC
SELECT 
-- Numero consecutivo
	PM.CONSECUTIVO F_NUMERO_REG,
	'0357' F_TIPO_REG,
	'00' F_SUBTIPO_REG,
	'03' F_VERSION_REG,
	@F_CIA F_CIA,
	@F_CONSEC_AUTO_REG F_CONSEC_AUTO_REG,
	RTRIM(V.f2181_id_co) F350_ID_CO,
	RTRIM(V.[f2181_id_tipo_docto_recibo]) F350_ID_TIPO_DOCTO,
	PM.CONSECUTIVO F350_CONSEC_DOCTO,
	--PM.FECHA_CREA F350_FECHA,
	PM.[FECHA_DESCARGA] F350_FECHA,
	RTRIM(v.f2181_id_caja) F357_ID_CAJA,
	PM.[FECHA_DESCARGA] F357_FECHA_RECAUDO,
	--PM.FECHA_CREA F357_FECHA_RECAUDO,
	LEFT(PM.CLIENTE_CODIGO, LEN(PM.CLIENTE_CODIGO) - 4) F350_ID_TERCERO,
	'COP' F357_ID_MONEDA_INGRESO,
	SUM(PI.VALOR_ABONO) F357_VALOR_INGRESO,
	'COP' F357_ID_MONEDA_APLICAR,
	--' ' F357_VALOR_APLICAR_REAL,
	SUM(PI.VALOR_ABONO) F357_VALOR_APLICAR_REAL,
	PM.VENDEDOR_CODIGO F357_ID_COBRADOR,
	'99' F357_ID_UN,
	' ' F357_ID_CCOSTO,
	@F357_ID_FE F357_ID_FE,
	@F350_ID_CLASE_DOCTO F350_ID_CLASE_DOCTO,
	@F350_IND_ESTADO F350_IND_ESTADO, 
	'1' F350_IND_IMPRESION,
	PM.PAGO_OBSERVACION F350_NOTAS,
	'53959501' F351_ID_AUXILIAR_AJUSTE,
	' ' F351_ID_CCOSTO_AJUSTE,
	'53053501' F351_ID_AUXILIAR_PP,
	' ' F351_ID_CCOSTO_PP,
	'42958101' F351_ID_AUXILIAR_OTRO_ING,
	C.NIT F351_ID_TERCERO_OTRO_ING,
	' ' F351_ID_SUCURSAL_OTRO_ING,
	' ' F351_ID_CO_OTRO_ING,
	' ' F351_ID_UN_OTRO_ING,
	' ' F351_ID_CCOSTO_OTRO_ING,
	PM.NUMERO_RECIBO_PAGO F357_REFERENCIA,
	@F357_IND_VALIDA_MEDPAGO F357_IND_VALIDA_MEDPAGO,
	' ' F350_ID_CO_RP,
	' ' F350_ID_TIPO_DOCTO_RP,
	'0' F350_CONSEC_DOCTO_RP,
	2 ORDEN,
	PM.PAGO_CODIGO
	INTO #AD_TBL_RC
FROM 
	PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
		PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
	INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
		PM.PAGO_CODIGO = PI.PAGO_CODIGO
	INNER JOIN CLIENTES C ON
		PM.CLIENTE_CODIGO = C.CLIENTE_CODIGO
	--INNER JOIN CAJAS_ERP CC  ON
	--	V.f2181_id_co = CC.[f291_id_co]
	--	and v.f2181_id_caja = cc.f291_id
WHERE
	PM.PROCESADO = 'N'
	--AND PM.VENDEDOR_CODIGO = 'YGM'
GROUP BY
	PM.CONSECUTIVO,
	V.f2181_id_co ,
	V.[f2181_id_tipo_docto_recibo],
	PM.CONSECUTIVO,
	PM.[FECHA_DESCARGA],
	RTRIM(v.f2181_id_caja),
	PM.FECHA_CREA,
	LEFT(PM.CLIENTE_CODIGO, LEN(PM.CLIENTE_CODIGO) - 4),
	PM.VENDEDOR_CODIGO,
	PM.PAGO_OBSERVACION,
	PM.NUMERO_RECIBO_PAGO,
	PM.PAGO_CODIGO,
	C.NIT

--INSERT INTO AD_TBL_RC_CAJA
SELECT
	PM.CONSECUTIVO F_NUMERO_REG,
	'0357' F_TIPO_REG,
	'01' F_SUBTIPO_REG,
	'03' F_VERSION_REG,
	@F_CIA F_CIA,
	RTRIM(V.f2181_id_co) F350_ID_CO,
	RTRIM(V.[f2181_id_tipo_docto_recibo]) F350_ID_TIPO_DOCTO,
	PM.CONSECUTIVO F350_CONSEC_DOCTO,
	--FP.FORMA_CODIGO 
	--'EFE' F358_ID_MEDIOS_PAGO,
	FORMA_CODIGO F358_ID_MEDIOS_PAGO,
	SUM(PI.VALOR_ABONO) F358_VALOR,
	' '  F358_ID_BANCO,
	' '  F358_NRO_CHEQUE,
	--case when FP.FORMA_CODIGO  in ('CON', 'TRA') then pm.NUMERO_TRANSFERENCIA else ' ' end 
	' ' F358_NRO_CUENTA,
	' ' F358_COD_SEGURIDAD,
	' ' F358_NRO_AUTORIZACION,
	' ' F358_FECHA_VCTO,
	--case when FP.FORMA_CODIGO  in ('CON', 'TRA') then pm.NUMERO_CHEQUE else ' ' end 
	CASE
		WHEN PM.FORMA_PAGO_CODIGO <> 'EFECTIVO' THEN PM.NUMERO_CHEQUE
		ELSE ' '
	END AS F358_REFERENCIA_OTROS,
	--' ' F358_REFERENCIA_OTROS,
	PM.FECHA_PAGO F358_FECHA_CONSIGNACION,
	' ' F358_ID_CAUSALES_DEVOLUCION,
	LEFT(PM.CLIENTE_CODIGO, LEN(PM.CLIENTE_CODIGO) - 4) F358_ID_TERCERO,
	' ' F358_NOTAS,
	' ' F358_ID_CCOSTO,
	' ' F358_NRO_ALT_DOCTO_BANCO,
	--' ' f358_DOCTO_BANCO_CG,
	CASE
		WHEN PM.FORMA_PAGO_CODIGO <> 'EFECTIVO' THEN 'CG'
		ELSE ' '
	END AS f358_DOCTO_BANCO_CG,
	ISNULL(CB.F026_ID,'') AS F358_ID_CTA_BANCARIA_CG,
	3 ORDEN,
	PM.PAGO_CODIGO
	INTO #AD_TBL_RC_CAJA
FROM 
	PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
		PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
	INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
		PM.PAGO_CODIGO = PI.PAGO_CODIGO
	INNER JOIN FORMAS_PAGO FP ON
		PM.EMPRESA_CODIGO = FP.EMPRESA_CODIGO AND
		PM.FORMA_PAGO_CODIGO = FP.FORMA_DESCRIPCION
	LEFT JOIN CUENTA_BANCOS CB ON
		PM.EMPRESA_CODIGO = CB.EMPRESA_CODIGO
		AND PM.CODIGO_BANCO = CB.F026_ID_BANCO
	--INNER JOIN CAJAS_ERP CC ON
	--	V.CENTRO_OPERACION = CC.[f291_id_co]
	--	and v.f2181_id_caja = cc.f291_id
	--INNER JOIN FORMAS_PAGO FP WITH(NOLOCK) ON
	--	PM.FORMA_PAGO_CODIGO = FP.FORMA_DESCRIPCION
	--	AND TIPO = 'R'
	--INNER JOIN BANCOS B ON
	--	B.[CODIGO_BANCO] = PM.CODIGO_BANCO
WHERE
	PM.PROCESADO = 'N'
	--AND PM.VENDEDOR_CODIGO = 'YGM'
GROUP BY
	PM.CONSECUTIVO,
	RTRIM(V.f2181_id_co),
	RTRIM(V.[f2181_id_tipo_docto_recibo]),
	PM.CONSECUTIVO,
	--FP.FORMA_CODIGO,
	--case when FP.FORMA_CODIGO  in ('CON', 'TRA') then pm.NUMERO_TRANSFERENCIA else ' ' end,
	--case when FP.FORMA_CODIGO  in ('CON', 'TRA') then pm.NUMERO_CHEQUE else ' ' end,
	pm.FECHA_PAGO,
	LEFT(PM.CLIENTE_CODIGO, LEN(PM.CLIENTE_CODIGO) - 4),
	PM.PAGO_CODIGO,
	FORMA_CODIGO,
	FP.FORMA_CODIGO,
	PM.FORMA_PAGO_CODIGO,
	PM.NUMERO_CHEQUE,
	CB.F026_ID
	
--INSERT INTO AD_TBL_RC_CXC



SELECT
	PM.CONSECUTIVO F_NUMERO_REG,
	'0357' F_TIPO_REG,
	'02' F_SUBTIPO_REG,
	'02' F_VERSION_REG,
	@F_CIA F_CIA,
	V.f2181_id_co F350_ID_CO,
	V.[f2181_id_tipo_docto_recibo] F350_ID_TIPO_DOCTO,
	PM.CONSECUTIVO F350_CONSEC_DOCTO,
	@F353_ID_AUXILIAR_DOCTO_CRUCE F353_ID_AUXILIAR_DOCTO_CRUCE,
	--V.f2181_id_co F353_ID_CO_DOCTO_CRUCE,
	--RIGHT(C.CENTRO_OPERACION, 3) F353_ID_CO_DOCTO_CRUCE,
	RTRIM(C.CENTRO_OPERACION) F353_ID_CO_DOCTO_CRUCE,
	--SA.f353_id_un_cruce F353_ID_UN_DOCTO_CRUCE,
	C.F353_ID_UN_CRUCE F353_ID_UN_DOCTO_CRUCE,
	RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))) F353_ID_SUCURSAL_DOCTO_CRUCE,
	LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1) F353_ID_TIPO_DOCTO_CRUCE,
	--LEFT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - 1) F353_CONSEC_DOCTO_CRUCE,
	RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))) F353_CONSEC_DOCTO_CRUCE,
	C.CUOTA F353_NRO_CUOTA_CRUCE,
	PI.VALOR_ABONO F354_VALOR_CR,
	--0 F354_VALOR_APLICADO_PP,
	PI.DESCUENTO F354_VALOR_APLICADO_PP,
	0 F354_VALOR_APROVECHA,
	--0 F354_VALOR_RETENCION,
	PI.RETE_FUENTE F354_VALOR_RETENCION,
	3 + ROW_NUMBER() OVER (PARTITION BY PM.CONSECUTIVO/*, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))*/ ORDER BY PM.CONSECUTIVO, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))) ORDEN,
	PM.PAGO_CODIGO
	INTO #AD_TBL_RC_CXC
FROM 
	PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
		PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
	INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
		PM.PAGO_CODIGO = PI.PAGO_CODIGO
	INNER JOIN CARTERA C WITH(NOLOCK) ON
		PI.NUMERO_DOCUMENTO = C.NUMERO_DOCUMENTO
		AND PM.VENDEDOR_CODIGO = C.VENDEDOR_CODIGO
		AND C.CLIENTE_CODIGO =PM.CLIENTE_CODIGO

		INNER JOIN CLIENTES CL  ON
		PM.CLIENTE_CODIGO = CL.CLIENTE_CODIGO		
		AND PM.EMPRESA_CODIGO = CL.EMPRESA_CODIGO

		--INNER JOIN  [SIESA-M1-SQLSW-DB13.CBM3OHOGEAJR.US-EAST-1.RDS.AMAZONAWS.COM].[UnoEE_Comoriente_Real].[dbo].t353_co_saldo_abierto  SA  WITH(NOLOCK) ON
		--SA.f353_id_cia = 001
		--AND SA.f353_id_sucursal COLLATE Modern_Spanish_CI_AS = RIGHT(PM.CLIENTE_CODIGO, 3)
		--AND SA.f353_id_tipo_docto_cruce COLLATE Modern_Spanish_CI_AS = LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1)
		--AND SA.f353_consec_docto_cruce = RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))
	--	AND SA.F353_rowid_tercero = C.f201_rowid_tercero






		--AND C.ESTADO = 'Y'
	--INNER JOIN CAJAS_ERP CC WITH(NOLOCK) ON
	--	V.CENTRO_OPERACION = CC.[f291_id_co]
	--	and v.f2181_id_caja = cc.f291_id
	--INNER JOIN FORMAS_PAGO FP WITH(NOLOCK) ON
	--	PM.FORMA_PAGO_CODIGO = FP.FORMA_DESCRIPCION
	--	AND TIPO = 'R'
	--INNER JOIN BANCOS B WITH(NOLOCK) ON
	--	B.[CODIGO_BANCO] = PM.CODIGO_BANCO
	--INNER JOIN UNOEE.DBO.t353_co_saldo_abierto SA  WITH(NOLOCK) ON
	--	SA.f353_id_cia = 4
	--	AND SA.f353_id_sucursal = RIGHT(PM.CLIENTE_CODIGO, 3)
	--	AND SA.f353_id_tipo_docto_cruce = LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1)
	--	AND SA.f353_consec_docto_cruce = RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))
WHERE
	PM.PROCESADO = 'N'
	--AND PM.VENDEDOR_CODIGO = 'YGM'



--INSERT INTO AD_TBL_RC_RETENCION


SELECT
	F_NUMERO_REG,
	'0357' F_TIPO_REG,
	'03' F_SUBTIPO_REG,
	'02' F_VERSION_REG,
	'001' F_CIA,
	F350_ID_CO,
	F350_ID_TIPO_DOCTO,
	F350_CONSEC_DOCTO,
	'13050501' F353_ID_AUXILIAR_DOCTO_CRUCE,
	F357_IND_VALIDA_MEDPAGO,
	F353_ID_UN_DOCTO_CRUCE,
	F353_ID_SUCURSAL_DOCTO_CRUCE,
	F353_ID_TIPO_DOCTO_CRUCE,
	F353_CONSEC_DOCTO_CRUCE,
	F353_NRO_CUOTA_CRUCE,
	F351_ID_AUXILIAR_RETENCION,
	'' F351_ID_CCOSTO_RETENCION,
	F354_VALOR_DB,
	0 F354_VALOR_CR,
	F351_BASE_GRAVABLE,
	3 + ORDEN AS ORDEN,
	PAGO_CODIGO
	INTO #AD_TBL_RC_RETENCION
FROM (
	-------------RETE FUENTE
	SELECT
		PM.CONSECUTIVO F_NUMERO_REG,
		V.f2181_id_co F350_ID_CO,
		V.[f2181_id_tipo_docto_recibo] F350_ID_TIPO_DOCTO,
		PM.CONSECUTIVO F350_CONSEC_DOCTO,
		C.CENTRO_OPERACION F357_IND_VALIDA_MEDPAGO,
		C.F353_ID_UN_CRUCE F353_ID_UN_DOCTO_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))) F353_ID_SUCURSAL_DOCTO_CRUCE,
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1) F353_ID_TIPO_DOCTO_CRUCE,
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))) F353_CONSEC_DOCTO_CRUCE,
		C.CUOTA F353_NRO_CUOTA_CRUCE,
		'13551501' F351_ID_AUXILIAR_RETENCION,
		PI.RETE_FUENTE F354_VALOR_DB,
		C.BASE_RETENCION F351_BASE_GRAVABLE,
		ROW_NUMBER() OVER (PARTITION BY PM.CONSECUTIVO/*, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))*/ ORDER BY PM.CONSECUTIVO, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))) AS ORDEN,
		PM.PAGO_CODIGO
	FROM
		PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
			PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
		INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
			PM.PAGO_CODIGO = PI.PAGO_CODIGO
		INNER JOIN CARTERA C WITH(NOLOCK) ON
			PI.NUMERO_DOCUMENTO = C.NUMERO_DOCUMENTO
			AND PM.VENDEDOR_CODIGO = C.VENDEDOR_CODIGO
			AND C.CLIENTE_CODIGO =PM.CLIENTE_CODIGO
			INNER JOIN CLIENTES CL  ON
		PM.CLIENTE_CODIGO = CL.CLIENTE_CODIGO
	WHERE 
		PI.RETE_FUENTE > 0
		AND PM.PROCESADO = 'N'
	GROUP BY
		PM.CONSECUTIVO,
		V.f2181_id_co,
		V.[f2181_id_tipo_docto_recibo],
		PM.CONSECUTIVO,
		C.CENTRO_OPERACION,
		C.F353_ID_UN_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))),
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1),
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))),
		C.CUOTA,
		--F351_ID_AUXILIAR_RETENCION,
		PI.RETE_FUENTE,
		C.BASE_RETENCION,
		PI.NUMERO_DOCUMENTO,
		PM.CONSECUTIVO,
		PM.PAGO_CODIGO

	UNION ALL

	-------------RETE IVA
	SELECT
		PM.CONSECUTIVO F_NUMERO_REG,
		V.f2181_id_co F350_ID_CO,
		V.[f2181_id_tipo_docto_recibo] F350_ID_TIPO_DOCTO,
		PM.CONSECUTIVO F350_CONSEC_DOCTO,
		C.CENTRO_OPERACION F357_IND_VALIDA_MEDPAGO,
		C.F353_ID_UN_CRUCE F353_ID_UN_DOCTO_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))) F353_ID_SUCURSAL_DOCTO_CRUCE,
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1) F353_ID_TIPO_DOCTO_CRUCE,
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))) F353_CONSEC_DOCTO_CRUCE,
		C.CUOTA F353_NRO_CUOTA_CRUCE,
		'13551701' F351_ID_AUXILIAR_RETENCION,
		PI.RETE_IVA F354_VALOR_DB,
		C.BASE_RETENCION F351_BASE_GRAVABLE,
		ROW_NUMBER() OVER (PARTITION BY PM.CONSECUTIVO/*, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))*/ ORDER BY PM.CONSECUTIVO, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))) AS ORDEN,
		PM.PAGO_CODIGO
	FROM
		PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
			PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
		INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
			PM.PAGO_CODIGO = PI.PAGO_CODIGO
		INNER JOIN CARTERA C WITH(NOLOCK) ON
			PI.NUMERO_DOCUMENTO = C.NUMERO_DOCUMENTO
			AND PM.VENDEDOR_CODIGO = C.VENDEDOR_CODIGO
			AND C.CLIENTE_CODIGO =PM.CLIENTE_CODIGO
			INNER JOIN CLIENTES CL  ON
		PM.CLIENTE_CODIGO = CL.CLIENTE_CODIGO
	WHERE 
		PI.RETE_IVA > 0
		AND PM.PROCESADO = 'N'
	GROUP BY
		PM.CONSECUTIVO,
		V.f2181_id_co,
		V.[f2181_id_tipo_docto_recibo],
		PM.CONSECUTIVO,
		C.CENTRO_OPERACION,
		C.F353_ID_UN_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))),
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1),
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))),
		C.CUOTA,
		--F351_ID_AUXILIAR_RETENCION,
		PI.RETE_IVA,
		C.BASE_RETENCION,
		PI.NUMERO_DOCUMENTO,
		PM.CONSECUTIVO,
		PM.PAGO_CODIGO

	UNION ALL

	-------------RETE ICA
	SELECT
		PM.CONSECUTIVO F_NUMERO_REG,
		V.f2181_id_co F350_ID_CO,
		V.[f2181_id_tipo_docto_recibo] F350_ID_TIPO_DOCTO,
		PM.CONSECUTIVO F350_CONSEC_DOCTO,
		C.CENTRO_OPERACION F357_IND_VALIDA_MEDPAGO,
		C.F353_ID_UN_CRUCE F353_ID_UN_DOCTO_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))) F353_ID_SUCURSAL_DOCTO_CRUCE,
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1) F353_ID_TIPO_DOCTO_CRUCE,
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))) F353_CONSEC_DOCTO_CRUCE,
		C.CUOTA F353_NRO_CUOTA_CRUCE,
		'13551801' F351_ID_AUXILIAR_RETENCION,
		PI.RETE_ICA F354_VALOR_DB,
		C.BASE_RETENCION F351_BASE_GRAVABLE,
		ROW_NUMBER() OVER (PARTITION BY PM.CONSECUTIVO/*, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))*/ ORDER BY PM.CONSECUTIVO, LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1), RIGHT(PI.NUMERO_DOCUMENTO, LEN(PI.NUMERO_DOCUMENTO) - PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO))) AS ORDEN,
		PM.PAGO_CODIGO
	FROM
		PAGO_MAST PM WITH(NOLOCK) INNER JOIN VENDEDORES_ERP V WITH(NOLOCK) ON
			PM.VENDEDOR_CODIGO = V.VENDEDOR_CODIGO
		INNER JOIN PAGO_ITEM PI WITH(NOLOCK) ON
			PM.PAGO_CODIGO = PI.PAGO_CODIGO
		INNER JOIN CARTERA C WITH(NOLOCK) ON
			PI.NUMERO_DOCUMENTO = C.NUMERO_DOCUMENTO
			AND PM.VENDEDOR_CODIGO = C.VENDEDOR_CODIGO
			AND C.CLIENTE_CODIGO =PM.CLIENTE_CODIGO
			INNER JOIN CLIENTES CL  ON
		PM.CLIENTE_CODIGO = CL.CLIENTE_CODIGO
	WHERE 
		PI.RETE_ICA > 0
		AND PM.PROCESADO = 'N'
	GROUP BY
		PM.CONSECUTIVO,
		V.f2181_id_co,
		V.[f2181_id_tipo_docto_recibo],
		PM.CONSECUTIVO,
		C.CENTRO_OPERACION,
		C.F353_ID_UN_CRUCE,
		RTRIM(isnull(C.[F353_ID_SUCURSAL], right(pm.cliente_codigo, 3))),
		LEFT(PI.NUMERO_DOCUMENTO, PATINDEX ('%-%' , PI.NUMERO_DOCUMENTO) - 1),
		RIGHT(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''), LEN(REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', '')) - PATINDEX ('%-%' , REPLACE(REPLACE(PI.NUMERO_DOCUMENTO, '-001', ''), '-002', ''))),
		C.CUOTA,
		--F351_ID_AUXILIAR_RETENCION,
		PI.RETE_ICA,
		C.BASE_RETENCION,
		PI.NUMERO_DOCUMENTO,
		PM.CONSECUTIVO,
		PM.PAGO_CODIGO
) AS X

	MERGE AD_TBL_RC AS T
	USING #AD_TBL_RC AS S
	ON 
		(
			T.[PAGO_CODIGO] = S.[PAGO_CODIGO]
		) 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT 
		(
			[F_NUMERO_REG],
			[F_TIPO_REG],
			[F_SUBTIPO_REG],
			[F_VERSION_REG],
			[F_CIA],
			[F_CONSEC_AUTO_REG],
			[F350_ID_CO],
			[F350_ID_TIPO_DOCTO],
			[F350_CONSEC_DOCTO],
			[F350_FECHA],
			[F357_ID_CAJA],
			[F357_FECHA_RECAUDO],
			[F350_ID_TERCERO],
			[F357_ID_MONEDA_INGRESO],
			[F357_VALOR_INGRESO],
			[F357_ID_MONEDA_APLICAR],
			[F357_VALOR_APLICAR_REAL],
			[F357_ID_COBRADOR],
			[F357_ID_UN],
			[F357_ID_CCOSTO],
			[F357_ID_FE],
			[F350_ID_CLASE_DOCTO],
			[F350_IND_ESTADO],
			[F350_IND_IMPRESION],
			[F350_NOTAS],
			[F351_ID_AUXILIAR_AJUSTE],
			[F351_ID_CCOSTO_AJUSTE],
			[F351_ID_AUXILIAR_PP],
			[F351_ID_CCOSTO_PP],
			[F351_ID_AUXILIAR_OTRO_ING],
			[F351_ID_TERCERO_OTRO_ING],
			[F351_ID_SUCURSAL_OTRO_ING],
			[F351_ID_CO_OTRO_ING],
			[F351_ID_UN_OTRO_ING],
			[F351_ID_CCOSTO_OTRO_ING],
			[F357_REFERENCIA],
			[F357_IND_VALIDA_MEDPAGO],
			[F350_ID_CO_RP],
			[F350_ID_TIPO_DOCTO_RP],
			[F350_CONSEC_DOCTO_RP],
			[ORDEN],
			[PAGO_CODIGO],
			[PROCESADO]
		)
		VALUES
		(
			S.[F_NUMERO_REG],
			S.[F_TIPO_REG],
			S.[F_SUBTIPO_REG],
			S.[F_VERSION_REG],
			S.[F_CIA],
			S.[F_CONSEC_AUTO_REG],
			S.[F350_ID_CO],
			S.[F350_ID_TIPO_DOCTO],
			S.[F350_CONSEC_DOCTO],
			S.[F350_FECHA],
			S.[F357_ID_CAJA],
			S.[F357_FECHA_RECAUDO],
			S.[F350_ID_TERCERO],
			S.[F357_ID_MONEDA_INGRESO],
			S.[F357_VALOR_INGRESO],
			S.[F357_ID_MONEDA_APLICAR],
			S.[F357_VALOR_APLICAR_REAL],
			S.[F357_ID_COBRADOR],
			S.[F357_ID_UN],
			S.[F357_ID_CCOSTO],
			S.[F357_ID_FE],
			S.[F350_ID_CLASE_DOCTO],
			S.[F350_IND_ESTADO],
			S.[F350_IND_IMPRESION],
			S.[F350_NOTAS],
			S.[F351_ID_AUXILIAR_AJUSTE],
			S.[F351_ID_CCOSTO_AJUSTE],
			S.[F351_ID_AUXILIAR_PP],
			S.[F351_ID_CCOSTO_PP],
			S.[F351_ID_AUXILIAR_OTRO_ING],
			S.[F351_ID_TERCERO_OTRO_ING],
			S.[F351_ID_SUCURSAL_OTRO_ING],
			S.[F351_ID_CO_OTRO_ING],
			S.[F351_ID_UN_OTRO_ING],
			S.[F351_ID_CCOSTO_OTRO_ING],
			S.[F357_REFERENCIA],
			S.[F357_IND_VALIDA_MEDPAGO],
			S.[F350_ID_CO_RP],
			S.[F350_ID_TIPO_DOCTO_RP],
			S.[F350_CONSEC_DOCTO_RP],
			S.[ORDEN],
			S.[PAGO_CODIGO],
			5
		);


	MERGE [AD_TBL_RC_CAJA] T
	USING #AD_TBL_RC_CAJA AS S
	ON 
		(
			T.[PAGO_CODIGO] = S.[PAGO_CODIGO]
		) 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT 
		(
			[F_NUMERO_REG],
			[F_TIPO_REG],
			[F_SUBTIPO_REG],
			[F_VERSION_REG],
			[F_CIA],
			[F350_ID_CO],
			[F350_ID_TIPO_DOCTO],
			[F350_CONSEC_DOCTO],
			[F358_ID_MEDIOS_PAGO],
			[F358_VALOR],
			[F358_ID_BANCO],
			[F358_NRO_CHEQUE],
			[F358_NRO_CUENTA],
			[F358_COD_SEGURIDAD],
			[F358_NRO_AUTORIZACION],
			[F358_FECHA_VCTO],
			[F358_REFERENCIA_OTROS],
			[F358_FECHA_CONSIGNACION],
			[F358_ID_CAUSALES_DEVOLUCION],
			[F358_ID_TERCERO],
			[F358_NOTAS],
			[F358_ID_CCOSTO],
			[F358_NRO_ALT_DOCTO_BANCO],
			[f358_DOCTO_BANCO_CG],
			[ORDEN],
			[PAGO_CODIGO],
			[F358_ID_CTA_BANCARIA_CG]
		)
		VALUES
		(
			S.[F_NUMERO_REG],
			S.[F_TIPO_REG],
			S.[F_SUBTIPO_REG],
			S.[F_VERSION_REG],
			S.[F_CIA],
			S.[F350_ID_CO],
			S.[F350_ID_TIPO_DOCTO],
			S.[F350_CONSEC_DOCTO],
			S.[F358_ID_MEDIOS_PAGO],
			S.[F358_VALOR],
			S.[F358_ID_BANCO],
			S.[F358_NRO_CHEQUE],
			S.[F358_NRO_CUENTA],
			S.[F358_COD_SEGURIDAD],
			S.[F358_NRO_AUTORIZACION],
			S.[F358_FECHA_VCTO],
			S.[F358_REFERENCIA_OTROS],
			S.[F358_FECHA_CONSIGNACION],
			S.[F358_ID_CAUSALES_DEVOLUCION],
			S.[F358_ID_TERCERO],
			S.[F358_NOTAS],
			S.[F358_ID_CCOSTO],
			S.[F358_NRO_ALT_DOCTO_BANCO],
			S.[f358_DOCTO_BANCO_CG],
			S.[ORDEN],
			S.[PAGO_CODIGO],
			S.[F358_ID_CTA_BANCARIA_CG]
		);

	MERGE [AD_TBL_RC_CXC] AS T
	USING #AD_TBL_RC_CXC AS S
	ON 
		(
			T.[PAGO_CODIGO] = S.[PAGO_CODIGO]
			AND T.[F_NUMERO_REG] = S.[F_NUMERO_REG]
			AND T.[F350_ID_TIPO_DOCTO] = S.[F350_ID_TIPO_DOCTO]
			AND T.[F350_CONSEC_DOCTO] = S.[F350_CONSEC_DOCTO]
			AND T.[F353_ID_TIPO_DOCTO_CRUCE] = S.[F353_ID_TIPO_DOCTO_CRUCE]
			AND T.[F353_CONSEC_DOCTO_CRUCE] = S.[F353_CONSEC_DOCTO_CRUCE]
		) 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT 
		(
			[F_NUMERO_REG],
			[F_TIPO_REG],
			[F_SUBTIPO_REG],
			[F_VERSION_REG],
			[F_CIA],
			[F350_ID_CO],
			[F350_ID_TIPO_DOCTO],
			[F350_CONSEC_DOCTO],
			[F353_ID_AUXILIAR_DOCTO_CRUCE],
			[F353_ID_CO_DOCTO_CRUCE],
			[F353_ID_UN_DOCTO_CRUCE],
			[F353_ID_SUCURSAL_DOCTO_CRUCE],
			[F353_ID_TIPO_DOCTO_CRUCE],
			[F353_CONSEC_DOCTO_CRUCE],
			[F353_NRO_CUOTA_CRUCE],
			[F354_VALOR_CR],
			[F354_VALOR_APLICADO_PP],
			[F354_VALOR_APROVECHA],
			[F354_VALOR_RETENCION],
			[ORDEN],
			[PAGO_CODIGO]
		)
		VALUES
		(
			S.[F_NUMERO_REG],
			S.[F_TIPO_REG],
			S.[F_SUBTIPO_REG],
			S.[F_VERSION_REG],
			S.[F_CIA],
			S.[F350_ID_CO],
			S.[F350_ID_TIPO_DOCTO],
			S.[F350_CONSEC_DOCTO],
			S.[F353_ID_AUXILIAR_DOCTO_CRUCE],
			S.[F353_ID_CO_DOCTO_CRUCE],
			S.[F353_ID_UN_DOCTO_CRUCE],
			S.[F353_ID_SUCURSAL_DOCTO_CRUCE],
			S.[F353_ID_TIPO_DOCTO_CRUCE],
			S.[F353_CONSEC_DOCTO_CRUCE],
			S.[F353_NRO_CUOTA_CRUCE],
			S.[F354_VALOR_CR],
			S.[F354_VALOR_APLICADO_PP],
			S.[F354_VALOR_APROVECHA],
			S.[F354_VALOR_RETENCION],
			S.[ORDEN],
			S.[PAGO_CODIGO]
		);

MERGE [AD_TBL_RC_RETENCION] AS T
	USING #AD_TBL_RC_RETENCION AS S
	ON 
		(
			T.[PAGO_CODIGO] = S.[PAGO_CODIGO]
			AND T.[F_NUMERO_REG] = S.[F_NUMERO_REG]
			AND T.[F350_ID_TIPO_DOCTO] = S.[F350_ID_TIPO_DOCTO]
			AND T.[F350_CONSEC_DOCTO] = S.[F350_CONSEC_DOCTO]
			AND T.[F353_ID_TIPO_DOCTO_CRUCE] = S.[F353_ID_TIPO_DOCTO_CRUCE]
			AND T.[F353_CONSEC_DOCTO_CRUCE] = S.[F353_CONSEC_DOCTO_CRUCE]
			AND T.[F351_ID_AUXILIAR_RETENCION] = S.[F351_ID_AUXILIAR_RETENCION]
		) 
	WHEN NOT MATCHED BY TARGET THEN 
		INSERT 
		(
			[F_NUMERO_REG],
			[F_TIPO_REG],
			[F_SUBTIPO_REG],
			[F_VERSION_REG],
			[F_CIA],
			[F350_ID_CO],
			[F350_ID_TIPO_DOCTO],
			[F350_CONSEC_DOCTO],
			[F353_ID_AUXILIAR_DOCTO_CRUCE],
			[F357_IND_VALIDA_MEDPAGO],
			[F353_ID_UN_DOCTO_CRUCE],
			[F353_ID_SUCURSAL_DOCTO_CRUCE],
			[F353_ID_TIPO_DOCTO_CRUCE],
			[F353_CONSEC_DOCTO_CRUCE],
			[F353_NRO_CUOTA_CRUCE],
			[F351_ID_AUXILIAR_RETENCION],
			[F351_ID_CCOSTO_RETENCION],
			[F354_VALOR_DB],
			[F354_VALOR_CR],
			[F351_BASE_GRAVABLE],
			[ORDEN],
			[PAGO_CODIGO]
		)
		VALUES
		(
			S.[F_NUMERO_REG],
			S.[F_TIPO_REG],
			S.[F_SUBTIPO_REG],
			S.[F_VERSION_REG],
			S.[F_CIA],
			S.[F350_ID_CO],
			S.[F350_ID_TIPO_DOCTO],
			S.[F350_CONSEC_DOCTO],
			S.[F353_ID_AUXILIAR_DOCTO_CRUCE],
			S.[F357_IND_VALIDA_MEDPAGO],
			S.[F353_ID_UN_DOCTO_CRUCE],
			S.[F353_ID_SUCURSAL_DOCTO_CRUCE],
			S.[F353_ID_TIPO_DOCTO_CRUCE],
			S.[F353_CONSEC_DOCTO_CRUCE],
			S.[F353_NRO_CUOTA_CRUCE],
			S.[F351_ID_AUXILIAR_RETENCION],
			S.[F351_ID_CCOSTO_RETENCION],
			S.[F354_VALOR_DB],
			S.[F354_VALOR_CR],
			S.[F351_BASE_GRAVABLE],
			S.[ORDEN],
			S.[PAGO_CODIGO]
		);



--SELECT * FROM #AD_TBL_RC
--SELECT * FROM #AD_TBL_RC_CAJA
--SELECT * FROM #AD_TBL_RC_CXC

--EXEC [DocumentoContableSIESAMerge]

UPDATE PAGO_MAST SET PROCESADO = 'S' WHERE CONSECUTIVO IN (SELECT F_NUMERO_REG FROM #AD_TBL_RC)


DROP TABLE #AD_TBL_RC
DROP TABLE #AD_TBL_RC_CAJA
DROP TABLE #AD_TBL_RC_CXC
DROP TABLE #AD_TBL_RC_RETENCION

END




