USE [COMORIENTE]
GO
/****** Object:  StoredProcedure [dbo].[sp_ad_inyecta_rc_Cloud]    Script Date: 12/07/2024 10:30:24 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[sp_ad_inyecta_rc_Cloud] 

AS
BEGIN
	SET NOCOUNT ON;


-------------------------------------------------------------------------------------------------------
-- Declara las variables de empresa en entero y texto
-------------------------------------------------------------------------------------------------------
	DECLARE @F_CIA VARCHAR(3) = '001'
	DECLARE @NF_CIA VARCHAR(3) = 1
	DECLARE @TOP INT = 1000

-------------------------------------------------------------------------------------------------------
-- se filtra el listado de pedidos a enviar a siesa excluyendo los ya enviados y los metemos a un cursor
-------------------------------------------------------------------------------------------------------
	DECLARE @PAGO_CODIGO VARCHAR(30),
			@CONSECUTIVO INT,
			@VENDEDOR_CODIGO VARCHAR(30),
			@CLIENTE_CODIGO VARCHAR(30),
			@CLIENTE_NOMBRE VARCHAR(300),
			@NUMERO_RECIBO_PAGO VARCHAR(30)

	DECLARE CRC CURSOR FOR SELECT TOP (@TOP)
		ATP.PAGO_CODIGO,
		PM.VENDEDOR_CODIGO,
		PM.CLIENTE_CODIGO,		
		C.CLIENTE_NOMBRE,
		PM.CONSECUTIVO,
		PM.NUMERO_RECIBO_PAGO
	FROM 
		AD_TBL_RC ATP INNER JOIN PAGO_MAST PM ON
			ATP.PAGO_CODIGO = PM.PAGO_CODIGO
		INNER JOIN CLIENTES C WITH(NOLOCK) ON
			PM.CLIENTE_CODIGO = C.CLIENTE_CODIGO
	WHERE 
		ATP.PROCESADO = 5

	ORDER BY PM.FECHA_CREA


	

	OPEN CRC 
	FETCH CRC INTO @PAGO_CODIGO, @VENDEDOR_CODIGO, @CLIENTE_CODIGO, @CLIENTE_NOMBRE, @CONSECUTIVO, @NUMERO_RECIBO_PAGO;
	WHILE (@@FETCH_STATUS = 0 )
	BEGIN
		DECLARE  @PLANO_RC TABLE([DETALLE] VARCHAR (MAX))
		DELETE FROM @PLANO_RC
		PRINT REPLICATE('=', 200)
		PRINT 'PROCESANDO EL DOCUMENTO ' + @NUMERO_RECIBO_PAGO + ' --> ' + CONVERT(VARCHAR, @CONSECUTIVO)
		PRINT 'VENDEDOR: ' + @VENDEDOR_CODIGO
		PRINT 'CLIENTE: ' + @CLIENTE_CODIGO + ' --> ' + UPPER(@CLIENTE_NOMBRE)

		PRINT 'ELIMINANDO PLANO_RC'
		


		DECLARE @RC VARCHAR(30) = CONVERT(VARCHAR, @CONSECUTIVO)
		PRINT 'GENERANDO PLANO'
		INSERT INTO @PLANO_RC

		SELECT CAST('00000010000000100' AS VARCHAR(MAX)) + CAST('1' AS VARCHAR(MAX))
		UNION ALL
		SELECT 
			-- [F_NUMERO_REG]
			RIGHT('0000000000' + CONVERT(VARCHAR, [ORDEN]), 7) +
			LEFT([F_TIPO_REG], 4) +
			LEFT([F_SUBTIPO_REG], 2) +
			LEFT([F_VERSION_REG], 2) +
			LEFT([F_CIA], 3) +
			LEFT([F_CONSEC_AUTO_REG], 1) +
			LEFT([F350_ID_CO], 3) +
			LEFT([F350_ID_TIPO_DOCTO] + '       ',3) +
			RIGHT('00000000' + CONVERT(VARCHAR, [F350_CONSEC_DOCTO]), 8) +
			LEFT(CAST (CONVERT (VARCHAR(8), [F350_FECHA], 112) AS VARCHAR (MAX)), 8) +
			LEFT([F357_ID_CAJA] + '          ', 3) +
			LEFT(CAST (CONVERT (VARCHAR(8), [F357_FECHA_RECAUDO], 112) AS VARCHAR (MAX)), 8) +
			LEFT([F350_ID_TERCERO] + '                    ', 15) +
			LEFT([F357_ID_MONEDA_INGRESO], 3) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F357_VALOR_INGRESO], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			LEFT([F357_ID_MONEDA_APLICAR], 3) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F357_VALOR_APLICAR_REAL], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			LEFT([F357_ID_COBRADOR] + '  ', 4) +
			LEFT([F357_ID_UN] + replicate(' ', 30), 20) +
			LEFT([F357_ID_CCOSTO] + '                               ', 15) +
			LEFT([F357_ID_FE] + '                               ', 13) +
			left([F350_ID_CLASE_DOCTO] + replicate(' ', 10), 5) +
			LEFT([F350_IND_ESTADO], 1) +
			LEFT([F350_IND_IMPRESION], 1) +
			LEFT([F350_NOTAS] + REPLICATE(' ', 255), 255) +
			LEFT([F351_ID_AUXILIAR_AJUSTE] + REPLICATE(' ', 20), 20) +
			LEFT([F351_ID_CCOSTO_AJUSTE] + REPLICATE(' ', 15), 15) +
			LEFT([F351_ID_AUXILIAR_PP] + REPLICATE(' ', 20), 20) +
			LEFT([F351_ID_CCOSTO_PP] + REPLICATE(' ', 15), 15) +
			LEFT([F351_ID_AUXILIAR_OTRO_ING] + REPLICATE(' ', 20), 20) +
			LEFT([F351_ID_TERCERO_OTRO_ING] + REPLICATE(' ', 15), 15) +
			LEFT([F351_ID_SUCURSAL_OTRO_ING] + REPLICATE(' ', 3), 3) +
			LEFT([F351_ID_CO_OTRO_ING] + REPLICATE(' ', 3), 3) +
			LEFT([F351_ID_UN_OTRO_ING] + REPLICATE(' ', 20), 20) +
			LEFT([F351_ID_CCOSTO_OTRO_ING] + REPLICATE(' ', 15), 15) +
			LEFT('RC-' + [F357_REFERENCIA] + REPLICATE(' ', 20), 20) +
			LEFT([F357_IND_VALIDA_MEDPAGO] + REPLICATE(' ', 20), 1) +
			LEFT([F350_ID_CO_RP] + REPLICATE(' ', 10), 3) +
			LEFT([F350_ID_TIPO_DOCTO_RP] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000' + CONVERT(VARCHAR, [F350_CONSEC_DOCTO_RP]), 8)	
		FROM 
			[AD_TBL_RC]
		WHERE
			[F_NUMERO_REG] = @RC
		UNION ALL
		SELECT 
			RIGHT('0000000' + CONVERT(VARCHAR, [ORDEN]), 7) +
			LEFT([F_TIPO_REG], 4) +
			LEFT([F_SUBTIPO_REG], 2) +
			LEFT([F_VERSION_REG], 2) +
			LEFT([F_CIA], 3) +
			LEFT([F350_ID_CO], 3) +
			LEFT([F350_ID_TIPO_DOCTO] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000' + CONVERT(VARCHAR, [F350_CONSEC_DOCTO]), 8) +
			LEFT([F358_ID_MEDIOS_PAGO] + REPLICATE(' ', 10), 3) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F358_VALOR], 2) AS DECIMAL(18,4)) AS VARCHAR),21)  +
			LEFT(CASE WHEN [F358_ID_MEDIOS_PAGO] = 'CHE' THEN [F358_ID_BANCO] + REPLICATE(' ', 10) ELSE REPLICATE(' ', 10) END, 10) +
			LEFT(/*[F358_NRO_CHEQUE] +*/ REPLICATE('0', 8), 8) +
			LEFT(CASE WHEN [F358_ID_MEDIOS_PAGO] = 'CHE' THEN [F358_NRO_CUENTA] + REPLICATE(' ', 35) ELSE REPLICATE(' ', 35) END, 25) +
			LEFT([F358_COD_SEGURIDAD] + REPLICATE(' ', 10), 3) +
			LEFT([F358_NRO_AUTORIZACION] + REPLICATE(' ', 10), 10) +
			LEFT([F358_FECHA_VCTO] + REPLICATE(' ', 10), 8) +
			LEFT([F358_REFERENCIA_OTROS] + REPLICATE(' ', 30), 30) +
			--CAST (CONVERT (VARCHAR(8), [F358_FECHA_CONSIGNACION], 112) AS VARCHAR (MAX)) +
			LEFT(CONVERT(INT, REPLACE(CONVERT(VARCHAR, [F358_FECHA_CONSIGNACION], 112), '-', '')), 8) +
			LEFT([F358_ID_CAUSALES_DEVOLUCION] + REPLICATE(' ', 10), 3) +
			LEFT([F358_ID_TERCERO] + REPLICATE(' ', 15), 15) + 
			LEFT([F358_NOTAS] + REPLICATE(' ', 255), 255) + 
			LEFT([F358_ID_CCOSTO] + REPLICATE(' ', 15), 15) +
			LEFT([F358_NRO_ALT_DOCTO_BANCO] + REPLICATE(' ', 30), 30) +
			LEFT([f358_DOCTO_BANCO_CG] + REPLICATE(' ', 2), 2)+
			LEFT([F358_ID_CTA_BANCARIA_CG] + REPLICATE(' ', 3), 3)
		FROM 
			[AD_TBL_RC_CAJA]
		WHERE
			[F_NUMERO_REG] = @RC
		UNION ALL
		SELECT
			RIGHT('0000000' + CONVERT(VARCHAR, [ORDEN]), 7) +
			[F_TIPO_REG] +
			[F_SUBTIPO_REG] +
			[F_VERSION_REG] +
			[F_CIA] +
			[F350_ID_CO] +
			LEFT([F350_ID_TIPO_DOCTO] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000' + CONVERT(VARCHAR, [F350_CONSEC_DOCTO]), 8) +
			LEFT([F353_ID_AUXILIAR_DOCTO_CRUCE] + REPLICATE(' ', 20), 20) +
			LEFT([F353_ID_CO_DOCTO_CRUCE] + REPLICATE(' ', 10), 3) +
			LEFT([F353_ID_UN_DOCTO_CRUCE] + REPLICATE(' ', 20), 20)+
			LEFT([F353_ID_SUCURSAL_DOCTO_CRUCE] + REPLICATE(' ', 10), 3) +
			LEFT([F353_ID_TIPO_DOCTO_CRUCE] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000'  + CONVERT(VARCHAR, [F353_CONSEC_DOCTO_CRUCE]), 8)  +
			LEFT('000' +  CONVERT(VARCHAR, [F353_NRO_CUOTA_CRUCE]), 3) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_CR], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_APLICADO_PP], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_APROVECHA], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_RETENCION], 2) AS DECIMAL(18,4)) AS VARCHAR),21) 
		FROM
			[AD_TBL_RC_CXC]
		WHERE
			[F_NUMERO_REG] = @RC
		UNION ALL
		SELECT
			RIGHT('0000000' + CONVERT(VARCHAR, [ORDEN] + ROW_NUMBER() OVER (ORDER BY [ORDEN])), 7)+
			[F_TIPO_REG] +
			[F_SUBTIPO_REG] +
			[F_VERSION_REG] +
			[F_CIA] +
			[F350_ID_CO] +
			LEFT([F350_ID_TIPO_DOCTO] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000' + CONVERT(VARCHAR, [F350_CONSEC_DOCTO]), 8) +
			LEFT([F353_ID_AUXILIAR_DOCTO_CRUCE] + REPLICATE(' ', 20), 20) +
			LEFT([F357_IND_VALIDA_MEDPAGO] + REPLICATE(' ', 20), 3) +
			LEFT([F353_ID_UN_DOCTO_CRUCE] + REPLICATE(' ', 20), 20)+
			LEFT([F353_ID_SUCURSAL_DOCTO_CRUCE] + REPLICATE(' ', 10), 3) +
			LEFT([F353_ID_TIPO_DOCTO_CRUCE] + REPLICATE(' ', 10), 3) +
			RIGHT('00000000'  + CONVERT(VARCHAR, [F353_CONSEC_DOCTO_CRUCE]), 8)  +
			LEFT('000' +  CONVERT(VARCHAR, [F353_NRO_CUOTA_CRUCE]), 3) +
			LEFT(CONVERT(VARCHAR, [F351_ID_AUXILIAR_RETENCION] + REPLICATE(' ', 20)), 20) +
			LEFT(CONVERT(VARCHAR, [F351_ID_CCOSTO_RETENCION] + REPLICATE(' ', 15)), 15) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_DB], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F354_VALOR_CR], 2) AS DECIMAL(18,4)) AS VARCHAR),21) +
			RIGHT(REPLICATE ('0', 15) + CAST ( CAST(ROUND([F351_BASE_GRAVABLE], 2) AS DECIMAL(18,4)) AS VARCHAR),21)		
		FROM
			[AD_TBL_RC_RETENCION]
		WHERE
			[F_NUMERO_REG] = @RC

		DECLARE @REG INT
		SELECT @REG = COUNT(*) + 1 FROM @PLANO_RC


		INSERT INTO @PLANO_RC SELECT REPLICATE('0',7-LEN(LTRIM(@REG))) + LTRIM(@REG) + '9999000100' + CAST('1' AS VARCHAR(MAX))
		DELETE FROM @PLANO_RC WHERE DETALLE IS NULL


					UPDATE ATP SET
					XML = P. XML,
					PROCESADO = 1
				FROM
					[AD_TBL_RC] ATP INNER JOIN  (
								
															SELECT DISTINCT
																PAGO_CODIGO, 
																'<Datos>' + REPLACE(REPLACE(LineasConcatenadas, '&lt;', '<'), '&gt;', '>') + '</Datos>' xml
															FROM
															(
																SELECT 
																	@PAGO_CODIGO PAGO_CODIGO,
																	(SELECT '' + ('<Linea>' + l.DETALLE + '</Linea>') FROM @PLANO_RC l FOR XML PATH('')) as LineasConcatenadas 
																FROM 
																	@PLANO_RC p 
					
															) X
														) P ON
						ATP.PAGO_CODIGO = P.PAGO_CODIGO

		
		FETCH CRC INTO @PAGO_CODIGO, @VENDEDOR_CODIGO, @CLIENTE_CODIGO, @CLIENTE_NOMBRE, @CONSECUTIVO, @NUMERO_RECIBO_PAGO;
	END
	CLOSE CRC
	DEALLOCATE CRC


end

