USE [BD]
GO

/****** Object:  View [dbo].[CARTERA_ERP]    Script Date: 20/05/2024 11:26:29 a. m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE VIEW [dbo].[CARTERA_ERP]
AS

SELECT 
	'816006362' AS [EMPRESA_CODIGO]
	,C.[CLIENTE_CODIGO] COLLATE Modern_Spanish_CI_AS AS [CLIENTE_CODIGO]
	,R.[VENDEDOR_CODIGO] COLLATE Modern_Spanish_CI_AS AS [VENDEDOR_CODIGO]
	,[COBRADOR_CODIGO] COLLATE Modern_Spanish_CI_AS AS [COBRADOR_CODIGO]
	,[TIPO_DOCUMENTO] COLLATE Modern_Spanish_CI_AS AS [TIPO_DOCUMENTO]
	,[NUMERO_DOCUMENTO] COLLATE Modern_Spanish_CI_AS AS [NUMERO_DOCUMENTO]
	,[FECHA_DOCUMENTO]
	,[FECHA_VENCIMIENTO]
	,[SALDO]
	,[OBSERVACIONES] COLLATE Modern_Spanish_CI_AS AS [OBSERVACIONES]
	,[BASE_RETENCION]
	,[VALOR_IMPUESTOS]
	,[SALDO_BASE]
	,[CUENTA_CONTABLE] COLLATE Modern_Spanish_CI_AS AS [CUENTA_CONTABLE]
	,C.[ESTADO] COLLATE Modern_Spanish_CI_AS AS [ESTADO]
	,CENTRO_OPERACION COLLATE Modern_Spanish_CI_AS AS [CENTRO_OPERACION]
	,CUOTA
	,SUCURSAL COLLATE Modern_Spanish_CI_AS AS [SUCURSAL]
FROM   
OPENQUERY ([SRVERP\SIESA],'
SELECT DISTINCT
	RTRIM(T.f200_nit) + ''-'' + RTRIM(C.f201_id_sucursal) [CLIENTE_CODIGO],
	ISNULL(RTRIM(C.f201_id_vendedor), ''-'') [VENDEDOR_CODIGO],
	ISNULL(ISNULL(RTRIM(C.f201_id_cobrador),  rTRIM(C.f201_id_vendedor)), ''-'')  [COBRADOR_CODIGO],
	RTRIM(CDC.F350_ID_TIPO_DOCTO) [TIPO_DOCUMENTO],
	RTRIM(CDC.F350_ID_TIPO_DOCTO) + ''-'' + CONVERT(VARCHAR, CDC.F350_CONSEC_DOCTO)  NUMERO_DOCUMENTO,

	CSA.f353_fecha [FECHA_DOCUMENTO],
	CSA.f353_fecha_vcto [FECHA_VENCIMIENTO],
	isnull(SUM(CSA.f353_total_db) - SUM(CSA.f353_total_cr) + SUM(CSA.f353_total_ch_postf),0) [SALDO],
	''Total Factura: '' + FORMAT(isnull(SUM(CSA.f353_total_db), 0), ''C'', ''es-co'') [OBSERVACIONES],
	0 [BASE_RETENCION],
	0 [VALOR_IMPUESTOS],
	isnull(SUM(CSA.f353_total_db), 0) [SALDO_BASE],
	LEFT(CAST (CONVERT (VARCHAR(8), [F353_FECHA_DSCTO_PP], 112) AS VARCHAR (MAX)), 8)[CUENTA_CONTABLE],
	''Y'' [ESTADO],
	RTRIM(CSA.[f353_id_co_cruce]) CENTRO_OPERACION,
	[f353_nro_cuota_cruce] CUOTA,
	F353_ID_SUCURSAL SUCURSAL
	--INTO CARTERA_TMP
	
from 
	[UnoEE_Real].[dbo].T350_CO_DOCTO_CONTABLE CDC INNER JOIN [UnoEE_Real].dbo.T351_CO_MOV_DOCTO CMD WITH(NOLOCK) ON
		CDC.f350_id_cia = CMD.f351_id_cia
		AND CMD.F351_ROWID_DOCTO = CDC.F350_ROWID
		AND CMD.f351_rowid_tercero = CDC.f350_rowid_tercero
	INNER JOIN [UnoEE_Real].[dbo].T353_CO_SALDO_ABIERTO CSA WITH(NOLOCK) ON
		CMD.f351_id_cia = CSA.f353_id_cia
		AND CMD.F351_ROWID = CSA.F353_ROWID_MOV_DOCTO
		AND CMD.f351_rowid_tercero = CSA.f353_rowid_tercero
		AND CMD.f351_id_sucursal = CSA.f353_id_sucursal
	INNER JOIN [UnoEE_Real].[dbo].t201_mm_clientes C WITH(NOLOCK) ON
		CSA.f353_id_cia = C.f201_id_cia
		AND CSA.f353_rowid_tercero = C.f201_rowid_tercero
		AND CSA.f353_id_sucursal = C.f201_id_sucursal
	INNER JOIN [UnoEE_Real].[dbo].t200_mm_terceros T WITH(NOLOCK) ON
		T.f200_id_cia = C.f201_id_cia 
		AND T.f200_rowid = C.f201_rowid_tercero
	--INNER JOIN (SELECT DISTINCT CLIENTE_CODIGO, VENDEDOR_CODIGO FROM RUTAS WHERE ESTADO = ''Y'') R ON
	--	RTRIM(T.f200_nit) + ''-'' + RTRIM(C.f201_id_sucursal) = R.CLIENTE_CODIGO
	
WHERE
	CDC.f350_id_cia = 1
	AND (CSA.f353_total_db - CSA.f353_total_cr) <> 0
	AND RTRIM(CDC.F350_ID_TIPO_DOCTO) IN (''FM'', ''FL'', ''NV'', ''NE'', ''NC0'')
	--and RTRIM(C.f201_id_vendedor) = ''1105''
	and RTRIM(T.f200_nit) + ''-'' + RTRIM(C.f201_id_sucursal) <> ''108791087988354-001''
GROUP BY
	RTRIM(T.f200_nit) + ''-'' + RTRIM(C.f201_id_sucursal),
	RTRIM(C.f201_id_vendedor),
	RTRIM(C.f201_id_cobrador),
	--R.VENDEDOR_CODIGO,--
	RTRIM(CDC.F350_ID_TIPO_DOCTO),
	RTRIM(CDC.F350_ID_TIPO_DOCTO) + ''-'' + CONVERT(VARCHAR, CDC.F350_CONSEC_DOCTO),
	CSA.f353_fecha,
	CSA.f353_fecha_vcto,
	LEFT(CAST (CONVERT (VARCHAR(8), [F353_FECHA_DSCTO_PP], 112) AS VARCHAR (MAX)), 8),
	RTRIM(CSA.[f353_id_co_cruce]),
	[f353_nro_cuota_cruce],
	F353_ID_SUCURSAL') AS C INNER JOIN RUTAS R
		ON C.[CLIENTE_CODIGO] COLLATE Modern_Spanish_CI_AS = R.[CLIENTE_CODIGO]

GO
